import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-[1rem] shadow-2xl mb-[-2rem] fixed w-full bg-gray-200">
          <Link href="/" className="text-decoration-none">
            <span className="text-blue-500 font-bold">Tutorial Website</span>
          </Link>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
